### ISSUE TITLE
Tests fail with pytest>=4.0 and python==3.6.7

### ISSUE THREAD

**Issue by mcgibbon** [astropy/pytest-arraydiff#18]
Master is currently failing in appveyor, seemingly due to a change in pytest 4.0.

Is this project active and accepting PRs? I may be able to contribute some dev time if we decide to use this.

**Comment by bsipocz** [comment]
@mcgibbon - yes, the project is active in the sense that it's actively used. So any fixes would be appreciated (we haven't seen any issues when using the plugin with newish pytest versions, so hopefully the reason for the failure is only a testing one rather than something in the code). 

Also, we haven't done it here yet, but since travis started to support windows we moved away from appveyor for most of the projects. If you're interested in updating the testing suite here, I would suggest using e.g. the http://github.com/astropy/pytest-doctestplus setup as a template.

**Comment by pllim** [comment]
We no longer use Appveyor. If you still have problem, please let us know and we can re-open this. Thanks!
